### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by AlynxZhou** [RimoChan/dota2-card#2]
"运行错误: TypeError(\"unsupported operand type(s) for //: 'NoneType' and 'int'\")"

链接是 https://dota.librian.net/api/d?id=399231943&%E8%A6%81=%E6%AF%94%E8%B5%9B,%E6%AF%94%E8%B5%9B%E6%97%B6%E9%95%BF

**Comment by AlynxZhou** [comment]
是要在设置里勾选公开比赛数据吗，我刚才勾了但是仍然没变化

**Comment by RimoChan** [comment]
好，我修好了！还有你怎么才打了1盘，要多打！

**Comment by AlynxZhou** [comment]
> 好，我修好了！还有你怎么才打了1盘，要多打！

你这图有问题吧，我最近没少打五黑啊！你这图要是没错我肯定要啊！

**Comment by RimoChan** [comment]
不知道啊，opendota就显示了一场比赛，是不是你以前的比赛没有公开数据所以它拿不到……

**Comment by AlynxZhou** [comment]
> 不知道啊，opendota就显示了一场比赛，是不是你以前的比赛没有公开数据所以它拿不到……

也不是没有可能，但是我最新一场应该是躺赢了（

总之先放几天看看

**Comment by AlynxZhou** [comment]
为啥我经常打开profile刷不出来呢（

**Comment by RimoChan** [comment]
大概是因为服务冷启动……

**Comment by RimoChan** [comment]
诶不对，服务挂了？
我晚上回去修理一下2333

**Comment by RimoChan** [comment]
又恢复了！
不知道发生了什么，就当作是冷启动时间太长了吧2333
